[package]
name = "ngtcp2"
version = "0.2.0"
description = "Rust bindings to ngtcp2 and nghttp3"
edition = "2024"
rust-version = "1.96"
publish = false
repository = { workspace = true }
readme = "README.md"
license-file = "LICENSE"

[lib]
name = "ngtcp2"
path = "src/lib.rs"

[dependencies]
aws-lc-rs = "=1.18.0"
aws-lc-sys = { version = "=0.44.0", features = ["ssl"] }
libc = "0.2"
nghttp3-sys = { workspace = true }
ngtcp2-sys = { workspace = true }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = ["Win32_Networking_WinSock"] }

[dev-dependencies]
rcgen = { workspace = true }
