[workspace]
members = [
    "http3",
    "http3-quic",
    "http3-datagram",

    # Internal
    "bench",
    "examples",
    "interop",
]
default-members = [
    "http3",
    "http3-quic",
    "http3-datagram",
    "examples",
]
exclude = [
  "fuzz",
  "interop/crates",
]
resolver = "2"

[workspace.package]
edition = "2024"
rust-version = "1.85"
repository = "https://github.com/0x676e67/http3"
license = "Apache-2.0"

[workspace.dependencies]
http3-datagram = { version = "0.0.2", path = "./http3-datagram" }
http3-quic = { version = "0.0.11", path = "./http3-quic" }
http3 = { version = "0.0.8", path = "http3" }

# Internal
ngtcp2-sys = "=0.2.0"
nghttp3-sys = "=0.2.0"
ngtcp2 = "=0.2.0"
tokio-ngtcp2 = "=0.2.0"

# External crates
anyhow = "1.0.104"
assert_matches = "1.5.0"
bytes = "1.12.1"
fastrand = "2.5.0"
futures = "0.3.33"
futures-util = { version = "0.3.33", default-features = false }
http = "1"
octets = "0.3.0"
pin-project-lite = { version = "0.2", default-features = false }
proptest = "1"
quic = { version = "0.11", default-features = false }
quinn = { version = "0.11", default-features = false }
quinn-proto = { version = "0.11", default-features = false }
rcgen = "=0.14.9"
rustls = { version = "0.23.42", default-features = false }
rustls-native-certs = "0.8"
smallvec = "1.15.0"
structopt = "0.3"
tokio = { version = "1.53.1", default-features = false }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3", default-features = false }
tracing-tree = "0.4"

[profile.bench]
opt-level = 3
codegen-units = 1
incremental = false

[patch.crates-io]
nghttp3-sys = { path = "interop/crates/nghttp3-sys" }
ngtcp2 = { path = "interop/crates/ngtcp2" }
ngtcp2-sys = { path = "interop/crates/ngtcp2-sys" }
