[package]
name = "http3-webtransport-rs"
version = "0.1.2"
rust-version = { workspace = true }
edition = { workspace = true }
documentation = "https://docs.rs/http3-webtransport-rs"
repository = { workspace = true }
readme = "readme.md"
description = "WebTransport extension for http3-rs"
keywords = ["http3", "quic", "webtransport"]
categories = ["network-programming", "web-programming"]
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = { workspace = true }
futures-util = { workspace = true }
http = { workspace = true }
pin-project-lite = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
http3-datagram-rs = { workspace = true }

[dependencies.http3-rs]
workspace = true
features = ["i-implement-a-third-party-backend-and-opt-into-breaking-changes"]
