[package]
name = "examples"
version = "0.0.0"
publish = false
# Dependabot creates a temporary src/main.rs while updating Cargo.lock. This
# package only has explicit examples, so do not infer an `examples` binary.
autobins = false
rust-version = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }

# If you copy one of the examples into a new project, you should be using
# [dependencies] instead.
[dev-dependencies]
anyhow = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
http3 = { workspace = true, features = ["tracing"] }
http3-quic = { workspace = true, features = ["tracing", "datagram"] }
http = { workspace = true }
quinn = { workspace = true, features = [
    "runtime-tokio",
    "rustls",
    "ring",
] }
rcgen = { workspace = true }
rustls = { workspace = true, features = [
    "logging",
    "ring",
    "std",
] }
rustls-native-certs = { workspace = true }
structopt = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = [
    "fmt",
    "ansi",
    "env-filter",
    "time",
    "tracing-log",
] }
octets = { workspace = true }

tracing-tree = { workspace = true }
http3-datagram = { workspace = true }

[features]
tree = []

[[example]]
name = "client"
path = "client.rs"

[[example]]
name = "server"
path = "server.rs"
