//! Extension traits for configuration types.
//!
//! Provides extension traits for configuration structs from ngtcp2-sys and
//! nghttp3-sys.
//!
//! # Why extension traits?
//!
//! Rust cannot add inherent methods to types defined by external crates because
//! of the orphan rule. `ngtcp2_transport_params` and `nghttp3_settings` are FFI
//! structs generated by bindgen in the `*-sys` crates, so this crate uses the
//! extension-trait pattern to provide builder-style configuration helpers.
//!
//! This gives us:
//!
//! - a fluent API such as `ngtcp2_transport_params::default_params().with_datagram(65535)`;
//! - less boilerplate when initializing FFI structs;
//! - one place to call versioned APIs such as `ngtcp2_transport_params_default_versioned`.

use nghttp3_sys::nghttp3_settings;
use ngtcp2_sys::ngtcp2_transport_params;

use crate::types::ConnectionId;

/// Extension trait for `nghttp3_settings`.
pub trait Http3SettingsExt {
    /// Creates default settings.
    fn default_settings() -> Self;

    /// Sets the maximum field section size.
    fn with_max_field_section_size(self, size: u64) -> Self;
}

impl Http3SettingsExt for nghttp3_settings {
    fn default_settings() -> Self {
        // Initialize through the versioned API first so newly added nghttp3
        // fields receive their library defaults before we override our values.
        let mut settings: Self = unsafe { std::mem::zeroed() };
        unsafe {
            nghttp3_sys::nghttp3_settings_default_versioned(
                nghttp3_sys::NGHTTP3_SETTINGS_VERSION as i32,
                &mut settings,
            );
        }
        settings.max_field_section_size = 64 * 1024; // 64 KB
        settings.qpack_max_dtable_capacity = 4096;
        settings.qpack_encoder_max_dtable_capacity = 4096;
        settings.qpack_blocked_streams = 100;
        settings
    }

    fn with_max_field_section_size(mut self, size: u64) -> Self {
        self.max_field_section_size = size;
        self
    }
}

/// Extension trait for `ngtcp2_transport_params`.
pub trait TransportParamsExt {
    /// Creates default transport parameters.
    fn default_params() -> Self;

    /// Sets the maximum idle timeout in nanoseconds.
    fn with_max_idle_timeout(self, timeout_ns: u64) -> Self;

    /// Sets the initial connection-level data limit.
    fn with_initial_max_data(self, max_data: u64) -> Self;

    /// Sets the maximum number of bidirectional streams.
    fn with_max_streams_bidi(self, max_streams: u64) -> Self;

    /// Sets the maximum number of unidirectional streams.
    fn with_max_streams_uni(self, max_streams: u64) -> Self;

    /// Enables QUIC DATAGRAM frames.
    fn with_datagram(self, max_size: u64) -> Self;

    /// Sets `original_dcid` for server-side connections.
    ///
    /// A server must set this field to the Destination Connection ID from the
    /// first Initial packet received from the client.
    fn with_original_dcid(self, dcid: &ConnectionId) -> Self;
}

impl TransportParamsExt for ngtcp2_transport_params {
    fn default_params() -> Self {
        // Start from ngtcp2's versioned defaults before applying local policy.
        let mut params: Self = unsafe { std::mem::zeroed() };
        unsafe {
            ngtcp2_sys::ngtcp2_transport_params_default_versioned(
                ngtcp2_sys::NGTCP2_TRANSPORT_PARAMS_VERSION as i32,
                &mut params,
            );
        }
        // Override the defaults with values suitable for local interop tests.
        params.initial_max_stream_data_bidi_local = 1024 * 1024; // 1 MB
        params.initial_max_stream_data_bidi_remote = 1024 * 1024; // 1 MB
        params.initial_max_stream_data_uni = 1024 * 1024; // 1 MB
        params.initial_max_data = 10 * 1024 * 1024; // 10 MB
        params.initial_max_streams_bidi = 100;
        params.initial_max_streams_uni = 100;
        params.max_idle_timeout = 30 * 1000 * 1000 * 1000; // 30 seconds in nanoseconds
        params.active_connection_id_limit = 8;
        params
    }

    fn with_max_idle_timeout(mut self, timeout_ns: u64) -> Self {
        self.max_idle_timeout = timeout_ns;
        self
    }

    fn with_initial_max_data(mut self, max_data: u64) -> Self {
        self.initial_max_data = max_data;
        self
    }

    fn with_max_streams_bidi(mut self, max_streams: u64) -> Self {
        self.initial_max_streams_bidi = max_streams;
        self
    }

    fn with_max_streams_uni(mut self, max_streams: u64) -> Self {
        self.initial_max_streams_uni = max_streams;
        self
    }

    fn with_datagram(mut self, max_size: u64) -> Self {
        self.max_datagram_frame_size = max_size;
        self
    }

    fn with_original_dcid(mut self, dcid: &ConnectionId) -> Self {
        self.original_dcid.datalen = dcid.len();
        self.original_dcid.data[..dcid.len()].copy_from_slice(dcid.as_bytes());
        self.original_dcid_present = 1;
        self
    }
}
