[package]
name = "http3-quinn-rs"
version = "0.0.10"
rust-version = { workspace = true }
authors = ["Jean-Christophe BEGUE <jc.begue@pm.me>"]
edition = { workspace = true }
documentation = "https://docs.rs/http3-quinn-rs"
repository = { workspace = true }
readme = "README.md"
description = "QUIC transport implementation based on Quinn."
keywords = ["http3", "quic"]
categories = ["network-programming", "web-programming"]
license = "MIT"

[dependencies]
http3-rs = { workspace = true }
bytes = { workspace = true }
quinn = { workspace = true, features = ["futures-io"] }
tokio-util = { workspace = true }
futures-util = { workspace = true }
http3-datagram-rs = { workspace = true, optional = true }
tracing = { workspace = true, optional = true }

[features]
tracing = ["dep:tracing"]
datagram = ["dep:http3-datagram-rs"]
